galaxy_info:
  author: Ingmar Renses
  description: Installeert en configureert Apache, PHP en php-mysql op Ubuntu webservers.
  company: Windesheim
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - noble

  galaxy_tags:
    - apache
    - php
    - webserver
    - ubuntu

dependencies: []