- name: Voorbereiding voor alle servers
  hosts: all
  become: true

  pre_tasks:
    - name: Update apt cache eenmalig
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

- name: Configureer webserver
  hosts: webservers
  become: true

  roles:
    - webserver

- name: Configureer databaseserver
  hosts: databaseservers
  become: true

  vars:
    mysql_user_name: dbuser
    mysql_user_password: dbpassword
    mysql_user_host: "%"

  roles:
    - database