---
galaxy_info:
  author: Ingmar Renses
  description: Installeert en configureert MySQL op Ubuntu databaseservers.
  company: Windesheim
  license: MIT
  min_ansible_version: "2.14"

  platforms:
    - name: Ubuntu
      versions:
        - noble

  galaxy_tags:
    - mysql
    - database
    - ubuntu

dependencies: []