---
- name: Configureer webserver met Galaxy role van collega
  hosts: webservers
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - role: DirectLogic.webserver

  post_tasks:
    - name: Controleer of Apache actief is
      ansible.builtin.service_facts:

    - name: Toon Apache status
      ansible.builtin.debug:
        msg: "Apache service is aanwezig op {{ inventory_hostname }}"
      when: "'apache2.service' in ansible_facts.services"

- name: Configureer databaseserver met Galaxy role van collega
  hosts: databaseservers
  become: true

  pre_tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600

  roles:
    - role: DirectLogic.database

  post_tasks:
    - name: Controleer of MySQL actief is
      ansible.builtin.service_facts:

    - name: Toon MySQL status
      ansible.builtin.debug:
        msg: "MySQL service is aanwezig op {{ inventory_hostname }}"
      when: "'mysql.service' in ansible_facts.services"